spring:
  application:
    name: FIM-SOLUTION-APPLICATION
  #  task:
  #    execution:
  #      pool:
  #        core-size: 4                # Number of core threads
  #        max-size: 8                 # Maximum number of threads
  #        queue-capacity: 50          # Size of the queue for waiting tasks
  #        keep-alive: 60              # Keep idle threads for 60 seconds before terminating
  datasource:
    url: jdbc:postgresql://localhost:5432/fimguide
    username: root
    password: root
    hikari:
      maximum-pool-size: 4           # Limited to match CPU core capacity
      minimum-idle: 8                # Maintain a few idle connections
      idle-timeout: 60000            # 60 seconds before idle connections are closed
      connection-timeout: 60000      # 60 seconds timeout for obtaining a connection
      max-lifetime: 1800000          # 30 minutes maximum lifetime of a connection
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true
        jdbc:
          batch_size: 100
        format_sql: true
        generate_statistics: false
        order_inserts: true
        order_updates: true
        dialect: org.hibernate.dialect.PostgreSQLDialect



